In [5]:
import sqlalchemy as sqla
db = sqla.create_engine('mssql+pymssql://sa:Aa1234@211.144.33.236:10081/JChainServiceLB')

In [6]:
import pandas as pd
pd.read_sql('''
            select * from F_ZPFRecorder
            ''', db)

,ID,EntenteID,Account_ID,SelfFlag,AccountPsCode,AccountPs,PFFund,SZFlag,BRNum,TraDepartId,...,Description,Cashier,CreateTime,ModifyTime,Status,IsUsingBT,JDDT,JSMode,SubAccount,SubAccount_ID
0,8,20170523065927,177,1,KH20170425-0005,爽歪歪,20.00,0,1,5000014,...,备注,SQWL,2017-05-23 06:59:38.037,2017-05-23 06:59:38.037,NaN,NaN,NaT,NaN,None,NaN
1,9,20170523071341,177,1,KH20170425-0005,爽歪歪,100.00,0,1,5000014,...,备注,SQWL,2017-05-23 07:13:48.513,2017-05-23 07:13:48.513,NaN,NaN,NaT,NaN,None,NaN
2,10,20170523071652,67,1,KH20170306-0008,东吴集团,100.00,0,1,5000014,...,备注,SQWL,2017-05-23 07:16:58.090,2017-05-23 07:16:58.090,NaN,NaN,NaT,NaN,None,NaN
3,11,20170523071723,67,1,KH20170306-0008,东吴集团,300.00,0,1,5000014,...,备注,SQWL,2017-05-23 07:17:25.090,2017-05-23 07:17:25.090,NaN,NaN,NaT,NaN,None,NaN
4,12,20170523132857709,216,1,SQWL00799,三国货运公司,4500.00,0,1,-1,...,,,2017-05-23 13:28:42.463,2017-05-23 13:28:42.463,NaN,NaN,NaT,NaN,None,NaN
5,13,20170523132930803,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 13:29:15.390,2017-05-23 13:29:15.390,NaN,NaN,NaT,NaN,None,NaN
6,14,20170523133204616,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 13:31:49.183,2017-05-23 13:31:49.183,NaN,NaN,NaT,NaN,None,NaN
7,15,20170523133226568,215,1,KH00010101-0249,外协优惠卷,3952.00,0,1,-1,...,,,2017-05-23 13:32:11.150,2017-05-23 13:32:11.150,NaN,NaN,NaT,NaN,None,NaN
8,16,20170523133337481,216,1,SQWL00799,三国货运公司,4570.00,0,1,-1,...,,,2017-05-23 13:33:22.063,2017-05-23 13:33:22.063,NaN,NaN,NaT,NaN,None,NaN
9,17,20170523133614542,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 13:35:59.103,2017-05-23 13:35:59.103,NaN,NaN,NaT,NaN,None,NaN
10,18,20170523134126542,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 13:41:11.090,2017-05-23 13:41:11.090,NaN,NaN,NaT,NaN,None,NaN
11,19,20170523134907628,215,1,KH00010101-0249,外协优惠卷,4020.00,0,1,-1,...,,,2017-05-23 13:48:52.160,2017-05-23 13:48:52.160,NaN,NaN,NaT,NaN,None,NaN
12,20,20170523135721605,216,1,SQWL00799,三国货运公司,4640.00,0,1,-1,...,,,2017-05-23 13:57:06.257,2017-05-23 13:57:06.257,NaN,NaN,NaT,NaN,None,NaN
13,21,20170523142934966,215,1,KH00010101-0249,外协优惠卷,0.02,0,1,-1,...,,,2017-05-23 14:29:19.533,2017-05-23 14:29:19.533,NaN,NaN,NaT,NaN,None,NaN
14,25,20170523144806253,108,1,KH20170327-0002,城际合同客户,0.02,0,1,-1,...,,,2017-05-23 14:47:50.650,2017-05-23 14:47:50.650,NaN,NaN,NaT,NaN,None,NaN
15,26,20170523145325056,215,1,KH00010101-0249,外协优惠卷,3908.00,0,1,-1,...,,,2017-05-23 14:53:09.437,2017-05-23 14:53:09.437,NaN,NaN,NaT,NaN,None,NaN
16,28,20170523152150116,215,1,KH00010101-0249,外协优惠卷,700.00,0,1,-1,...,,,2017-05-23 15:21:34.427,2017-05-23 15:21:34.427,NaN,NaN,NaT,NaN,None,NaN
17,29,20170523152227652,215,1,KH00010101-0249,外协优惠卷,1000.00,0,1,-1,...,,,2017-05-23 15:22:11.950,2017-05-23 15:22:11.950,NaN,NaN,NaT,NaN,None,NaN
18,31,20170523161255945,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 16:12:40.277,2017-05-23 16:12:40.277,38.0,NaN,NaT,NaN,None,NaN
19,32,20170523161426282,22,1,KH20170210-0002,物流,-7000.00,0,1,-1,...,,,2017-05-23 16:14:10.457,2017-05-23 16:14:10.457,NaN,NaN,NaT,NaN,None,NaN
20,33,20170523161555566,216,1,SQWL00799,三国货运公司,4530.00,0,1,-1,...,,,2017-05-23 16:15:39.730,2017-05-23 16:15:39.730,38.0,NaN,NaT,NaN,None,NaN
21,34,20170523161643071,216,1,SQWL00799,三国货运公司,-4530.00,0,1,-1,...,,,2017-05-23 16:16:27.230,2017-05-23 16:16:27.230,NaN,NaN,NaT,NaN,None,NaN
22,35,20170523161646557,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 16:16:30.743,2017-05-23 16:16:30.743,38.0,NaN,NaT,NaN,None,NaN
23,36,20170523161731737,22,1,KH20170210-0002,物流,-7000.00,0,1,-1,...,,,2017-05-23 16:17:15.907,2017-05-23 16:17:15.907,NaN,NaN,NaT,NaN,None,NaN
24,37,20170523161957852,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 16:19:42.010,2017-05-23 16:19:42.010,NaN,NaN,NaT,NaN,None,NaN
25,38,20170523162143700,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 16:21:27.850,2017-05-23 16:21:27.850,38.0,NaN,NaT,NaN,None,NaN
26,39,20170523162357988,22,1,KH20170210-0002,物流,-7000.00,0,1,-1,...,,,2017-05-23 16:23:42.137,2017-05-23 16:23:42.137,NaN,NaN,NaT,NaN,None,NaN
27,40,20170523162609137,22,1,KH20170210-0002,物流,7000.00,0,1,-1,...,,,2017-05-23 16:25:53.283,2017-05-23 16:25:53.283,38.0,NaN,NaT,NaN,None,NaN
28,41,20170523162643272,22,1,KH20170210-0002,物流,-7000.00,0,1,-1,...,,,2017-05-23 16:26:27.417,2017-05-23 16:26:27.417,NaN,NaN,NaT,NaN,None,NaN
29,42,20170523164215058,216,1,SQWL00799,三国货运公司,4510.00,0,1,-1,...,,,2017-05-23 16:41:59.170,2017-05-23 16:41:59.170,38.0,NaN,NaT,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143,43637,20171017115856,463,3,CBS01297,王沙（承包商）,-500.00,0,1,5000022,...,备注,SQWL,2017-10-17 11:59:18.013,2017-10-17 11:59:18.013,0.0,0.0,NaT,NaN,None,NaN
3144,43638,20171017154232,423,3,CBS01289,徐世乐测试,6000.00,0,1,1008887,...,备注,SQWL,2017-10-17 15:42:25.330,2017-10-17 15:42:25.330,0.0,0.0,NaT,NaN,None,NaN
3145,43639,20171017155815391,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-17 15:57:17.517,2017-10-17 15:57:17.517,0.0,0.0,NaT,NaN,None,NaN
3146,43640,20171017155903565,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-17 15:58:05.670,2017-10-17 15:58:05.670,0.0,0.0,NaT,NaN,None,NaN
3147,43641,20171017155931167,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-17 15:58:33.267,2017-10-17 15:58:33.267,0.0,0.0,NaT,NaN,None,NaN
3148,43642,20171017155948552,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-17 15:58:50.643,2017-10-17 15:58:50.643,0.0,0.0,NaT,NaN,None,NaN
3149,43643,20171018144646418,213,1,KH20170518-0003,外协优惠卷激活,7100.00,0,1,-1,...,,,2017-10-18 14:45:45.360,2017-10-18 14:45:45.360,38.0,0.0,NaT,NaN,None,NaN
3150,43644,20171018150337619,213,1,KH20170518-0003,外协优惠卷激活,-7100.00,0,1,-1,...,,,2017-10-18 15:02:36.480,2017-10-18 15:02:36.480,40.0,0.0,NaT,NaN,None,NaN
3151,43645,20171018165820,478,3,CBS01300,杨宪军,-8000.00,0,1,1008888,...,备注,SQWL,2017-10-18 17:07:05.720,2017-10-18 17:07:05.720,0.0,0.0,NaT,NaN,None,NaN
3152,43646,20171018171035,478,3,CBS01300,杨宪军,-10500.00,0,1,1008888,...,备注,SQWL,2017-10-18 17:11:55.847,2017-10-18 17:11:55.847,0.0,0.0,NaT,NaN,None,NaN
3153,43647,20171018172230,463,3,CBS01297,王沙（承包商）,-500.00,0,1,1008888,...,备注,SQWL,2017-10-18 17:24:29.520,2017-10-18 17:24:29.520,0.0,0.0,2017-10-18 17:22:00,NaN,None,NaN
3154,43648,20171018180415,104,3,CBS01238,金海承包商,500.00,0,1,1008888,...,备注,SQWL,2017-10-18 18:04:29.050,2017-10-18 18:04:29.050,0.0,1.0,2017-10-18 18:04:00,NaN,None,NaN
3155,43649,20171018182209,104,3,CBS01238,金海承包商,600.00,0,1,1008888,...,备注,SQWL,2017-10-18 18:22:41.113,2017-10-18 18:22:41.113,0.0,0.0,2017-10-18 18:22:00,0.0,,0.0
3156,43650,20171019104548,104,3,CBS01238,金海承包商,5.00,0,1,1008888,...,备注,SQWL,2017-10-19 10:46:36.433,2017-10-19 10:46:36.433,0.0,0.0,2017-10-18 00:00:00,0.0,,0.0
3157,43651,20171019104805,104,3,CBS01238,金海承包商,600.00,0,1,1008888,...,备注,SQWL,2017-10-19 10:48:59.577,2017-10-19 10:48:59.577,0.0,0.0,2017-10-20 00:00:00,0.0,,0.0
3158,43652,20171019134333655,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-19 13:42:56.440,2017-10-19 13:42:56.440,0.0,0.0,NaT,0.0,,0.0
3159,43653,20171019134649270,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-19 13:46:12.030,2017-10-19 13:46:12.030,0.0,0.0,NaT,0.0,,0.0
3160,43654,20171019134850831,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-19 13:48:13.597,2017-10-19 13:48:13.597,0.0,0.0,NaT,0.0,,0.0
3161,43655,20171019135009968,22,1,KH20170210-0002,物流,8200.00,0,1,-1,...,,,2017-10-19 13:49:32.733,2017-10-19 13:49:32.733,0.0,0.0,NaT,0.0,,0.0
3162,43656,20171019143823,355,3,CBS01270,一直往南方开,-2300.00,0,1,1008888,...,备注,SQWL,2017-10-19 14:39:14.580,2017-10-19 14:39:14.580,0.0,0.0,2017-10-19 14:38:00,0.0,,0.0
3163,43657,20171019144329,161,1,KH20170401-0003,养乐多,-222.00,0,1,5000036,...,备注,SQWL,2017-10-19 14:49:33.160,2017-10-19 14:49:33.160,0.0,0.0,NaT,0.0,,0.0
3164,43658,20171019144423,317,1,KH20170627-0002,ABC物流公司,1000.00,0,1,5000037,...,备注,SQWL,2017-10-19 14:50:17.137,2017-10-19 14:50:17.137,0.0,0.0,2017-10-19 14:44:00,0.0,,0.0
3165,43659,20171019144552,161,1,KH20170401-0003,养乐多,200.00,0,1,5000037,...,备注,SQWL,2017-10-19 14:51:44.873,2017-10-19 14:51:44.873,0.0,0.0,2017-10-02 00:00:00,0.0,,0.0
3166,43660,20171019144620,216,1,SQWL00799,三国货运公司,-10.00,0,1,5000036,...,备注,SQWL,2017-10-19 14:52:36.167,2017-10-19 14:52:36.167,0.0,0.0,2017-10-19 14:46:00,0.0,,0.0
3167,43661,20171019150443,22,1,KH20170210-0002,物流,-3200.00,0,1,5000039,...,备注,SQWL,2017-10-19 15:10:33.207,2017-10-19 15:10:33.207,0.0,0.0,NaT,0.0,,0.0
3168,43662,20171019150535,355,3,CBS01270,一直往南方开,5555.00,0,1,5000038,...,备注,SQWL,2017-10-19 15:11:25.197,2017-10-19 15:11:25.197,0.0,0.0,2017-10-19 15:05:00,0.0,,0.0
3169,43663,20171019150623,466,3,CBS01274,包氏,225.40,0,1,5000038,...,备注,SQWL,2017-10-19 15:12:12.667,2017-10-19 15:12:12.667,0.0,0.0,2017-10-19 15:06:00,0.0,,0.0
3170,43664,20171019174224524,213,1,KH20170518-0003,外协优惠卷激活,7103.50,0,1,-1,...,,,2017-10-19 17:41:46.790,2017-10-19 17:41:46.790,0.0,0.0,NaT,0.0,,0.0
3171,53664,20171020105102084,449,1,KH20170913-0002,封巧丽,-1.00,0,1,-1,...,,,2017-10-20 10:50:08.420,2017-10-20 10:50:08.420,40.0,0.0,NaT,0.0,,0.0
3172,53665,20171020114535503,22,1,KH20170210-0002,物流,0.10,0,1,-1,...,,,2017-10-20 11:44:41.850,2017-10-20 11:44:41.850,0.0,0.0,NaT,0.0,,0.0